site_name: Aarhus Stadsarkiv
repo_url: https://github.com/aarhusstadsarkiv/acadocs
repo_name: aarhusstadsarkiv/acadocs
site_author: Claus Juhl Knudsen
site_description: >-
  Documentation for some of the digital processes that we often
  work with at Aarhus City Archives.

nav:
  # - Udvælgelse:
  #   - Introduktion: selection/index.md
  # - Modtagelse:
  #   - Introduktion: acquisition/index.md
  #   - Analog materiale: acquisition/acquiring-analog-material.md
  #   - Digitalt materiale: acquisition/acquiring-digital-material.md
  # - Digitalisering:
  #   - Introduktion: digitization/index.md
  - Registrering:
    - Introduktion: registration/index.md
    - SAM:
      - Introduktion: registration/sam/index.md
      - Installation: registration/sam/installation.md
      - Eksport af metadata: registration/sam/export.md
      - Import af metadata: registration/sam/import.md
    - SAM-Workflows:
      - Introduktion: registration/sam-workflows/index.md
      - Installation: registration/sam-workflows/installation.md
      - Generering af access-filer:  registration/sam-workflows/generate-access-files.md

  # - Tilgængeliggørelse:
  #   - Introduktion: dissemination/index.md
  - Hjemmesider:
    - AarhusArkivet: sites/aarhusarkivet.md
    - AarhusWiki: sites/aarhuswiki.md
    - Smartarkivering:
      - Hent data: sites/smartarkivering/fetch-data-via-ftp.md
      - Kør workflow: sites/smartarkivering/run-workflow.md
      - Forbered data: sites/smartarkivering/proces-raw-data.md
      - Importér til SAM: sites/smartarkivering/import-to-sam.md
    - Byrådsarkivet:
      - Publicér ny version: sites/byraadsarkivet/deploy-new-version.md
  # Værktøjer, CLIs, GUI-applikationer, online services...
  - Software:
    - Introduktion: software/index.md
    - FileZilla: software/filezilla.md
    - Chocolatey: software/chocolatey.md
    - Digiarch: software/digiarch.md
    - Convertool: software/convertool.md
    - Symphovert: software/symphovert.md
    - Ghostscript: software/ghostscript.md
    - LibreOffice: software/libreoffice.md
  # - Blanketter:
  #   - Introduktion: documents/index.md
  - Arkiveringsversioner:
    - Introduktion: archival-versions/index.md
    - Notesarkivering: archival-versions/notes-arkivering.md
  # - Diverse:
  #   - diverse/archiving_practices.md
  #   - diverse/database_tables.md
  #   - diverse/framework.md
  - Dev:
      - development/github.md
      - development/pyinstaller.md
      - Diverse: diverse/index.md
extra_css:
  - css/extra.css
theme:
  name: material
  font: false
  language: da
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.instant
  custom_dir: overrides
plugins:
  # https://squidfunk.github.io/mkdocs-material/reference/variables/#macros
  - macros
  - search:
      lang: da
# Place any global vars here (macros-plugin can fetch them) to use in jinja
# extra:
#   unit:
#     price: 12
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - meta
  - def_list
  # Alerts
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
  - admonition 
  # Make alerts collapsible
  - pymdownx.details
  - pymdownx.superfences
  # Align images left or right
  # E.g. ![Placeholder](https://dummyimage.com/600x400/eee/aaa){: align=left }
  - attr_list
