name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - uses: abatilo/actions-poetry@v2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - run: poetry install
      - name: Build
        run: poetry run mkdocs build
      - name: Save Site Artifact
        uses: actions/upload-artifact@v3
        with:
          name: acadocs
          path: site

